esphome:
  name: greenhouse-1
  friendly_name: Greenhouse 1
  area: farm
  platformio_options:
    platform: espressif32
    board: az-delivery-devkit-v4

esp32:
  board: az-delivery-devkit-v4

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret ha_api_key

ota:
  - platform: esphome
    password: !secret ha_ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_passphrase

  # Enable fallback hotspot
  ap:
    ssid: !secret wifi_fallback_ssid
    password: !secret wifi_fallback_passphrase

web_server:
  port: 80

# Sync time with Home Assistant
time:
  - platform: homeassistant
    id: homeassistant_time

# Text sensors with general information
text_sensor:
  # Expose ESPHome version as sensor
  - platform: version
    name: ESPHome Version

i2c:
  sda: 21
  scl: 22
  scan: true
  id: bus_a

sensor:
  - platform: bme280_i2c
    temperature:
      name: "BME280 Temperature"
      id: bme280_temperature
    pressure:
      name: "BME280 Pressure"
      id: bme280_pressure
    humidity:
      name: "BME280 Relative Humidity"
      id: bme280_humidity
    address: 0x76
    update_interval: 15s

  - platform: dallas_temp
    address: 0x7828934b0a646128
    name: Ground Temperature 10cm
    update_interval: 600s

  - platform: dallas_temp
    address: 0x9d041670d5b5ff28
    name: Ground Temperature 50cm
    update_interval: 600s

  - platform: uptime
    type: seconds
    name: Uptime Sensor

  # Reports the WiFi signal strength/RSSI in dB
  - platform: wifi_signal
    name: "WiFi Signal dB"
    id: wifi_signal_db
    update_interval: 60s
    entity_category: "diagnostic"

  # Reports the WiFi signal strength in %
  - platform: copy
    source_id: wifi_signal_db
    name: "WiFi Signal Percent"
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: "Signal %"
    entity_category: "diagnostic"
    device_class: ""

light:
  - platform: status_led
    name: "Power State LED"
    pin: GPIO32
  - platform: status_led
    name: "Network State LED"
    pin: GPIO33

one_wire:
  - platform: gpio
    pin: GPIO27
